// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/VolkovEgor/sellerx-task/internal/repository (interfaces: Chat)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/VolkovEgor/sellerx-task/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockChat is a mock of Chat interface.
type MockChat struct {
	ctrl     *gomock.Controller
	recorder *MockChatMockRecorder
}

// MockChatMockRecorder is the mock recorder for MockChat.
type MockChatMockRecorder struct {
	mock *MockChat
}

// NewMockChat creates a new mock instance.
func NewMockChat(ctrl *gomock.Controller) *MockChat {
	mock := &MockChat{ctrl: ctrl}
	mock.recorder = &MockChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChat) EXPECT() *MockChatMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChat) Create(arg0 *model.Chat) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChatMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChat)(nil).Create), arg0)
}

// ExistenceCheck mocks base method.
func (m *MockChat) ExistenceCheck(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistenceCheck", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExistenceCheck indicates an expected call of ExistenceCheck.
func (mr *MockChatMockRecorder) ExistenceCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistenceCheck", reflect.TypeOf((*MockChat)(nil).ExistenceCheck), arg0)
}

// GetAllForUser mocks base method.
func (m *MockChat) GetAllForUser(arg0 string) ([]*model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForUser", arg0)
	ret0, _ := ret[0].([]*model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForUser indicates an expected call of GetAllForUser.
func (mr *MockChatMockRecorder) GetAllForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForUser", reflect.TypeOf((*MockChat)(nil).GetAllForUser), arg0)
}

// GetById mocks base method.
func (m *MockChat) GetById(arg0 string) (*model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0)
	ret0, _ := ret[0].(*model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockChatMockRecorder) GetById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockChat)(nil).GetById), arg0)
}
